### ISSUE TITLE
Cyrillic symbols

### ISSUE THREAD

**Issue by BerNardEr** [RFO-BASIC/De-Re-Basic#97]
Print can't display cyrillic symbols(when getting them with ftp, for example), is it fixable?

**Comment by jMarcS** [comment]
This is the Issues list for the manual, De-Re-Basic. In the future please post in RFO-BASIC/Basic.

Print can display Cyrillic symbols. `PRINT CHR$(1046)` prints `Ж`. So the problem is not in the print command, it is in the code that feeds the print command.

I don't know what you mean by "getting them with ftp". ftp gets files. How are you reading the data? Can you show me some of your code?

**Comment by BerNardEr** [comment]
Sorry, I meant, that i was getting text files with ftp and reading some text from them with grabfile.

**Comment by jMarcS** [comment]
Okay, thanks. Grabfile assumes binary files. There is an optional parameter to tell it you are reading an encoded text file. `GRABFILE, string$, filename$, 1` The manual calls it the "unicode_flag_lexp".

If you are setting the optional text flag, then something else is wrong. When the text flag is set, grabfile assumes the input file is UTF-8 encoded. Maybe the input is something else.

So, two questions: 1) are you setting the text flag on grabfile, and 2) do you know the input file encoding?

**Comment by BerNardEr** [comment]
Yes, the file is UTF-8 encoded. I forgot about text flag. Thank you, I'll try it.
